import type { Brand, Car, Location } from './rentals';
import { d } from './helpers';

export const locations: Location[] = [
  { id: 'loc-bel-air', city: 'Belgrade', name: 'Airport Nikola Tesla' },
  { id: 'loc-bel-centar', city: 'Belgrade', name: 'City Center' },
  { id: 'loc-ns-centar', city: 'Novi Sad', name: 'City Center' },
  { id: 'loc-nis-centar', city: 'Niš', name: 'City Center' },
];

export const cars: Car[] = [
  {
    id: 'car-001',
    make: 'Toyota',
    model: 'Corolla',
    year: 2022,
    fuel: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 6.5,
    pickupLocationIds: ['loc-bel-air', 'loc-bel-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-bel-centar', 'loc-ns-centar'],
    bookings: [
      {
        carId: 'car-001',
        pickupLocationId: 'loc-bel-air',
        returnLocationId: 'loc-bel-centar',
        start: d('2025-08-12T08:00:00Z'),
        end: d('2025-08-12T16:00:00Z'),
      },
      {
        carId: 'car-001',
        pickupLocationId: 'loc-bel-centar',
        returnLocationId: 'loc-bel-centar',
        start: d('2025-08-14T09:00:00Z'),
        end: d('2025-08-14T12:00:00Z'),
      },
    ],
    imageUrl: 'images/cars/corolla-2022.jpg',
  },
  {
    id: 'car-002',
    make: 'Volkswagen',
    model: 'Golf',
    year: 2021,
    fuel: 'diesel',
    transmission: 'manual',
    seats: 5,
    pricePerHour: 5.2,
    pickupLocationIds: ['loc-bel-centar', 'loc-ns-centar'],
    returnLocationIds: ['loc-bel-centar', 'loc-ns-centar', 'loc-nis-centar'],
    bookings: [
      {
        carId: 'car-002',
        pickupLocationId: 'loc-bel-centar',
        returnLocationId: 'loc-ns-centar',
        start: d('2025-08-11T10:00:00Z'),
        end: d('2025-08-11T18:00:00Z'),
      },
    ],
    imageUrl: 'images/cars/golf-2021.jpg',
  },
  {
    id: 'car-003',
    make: 'Hyundai',
    model: 'i30',
    year: 2023,
    fuel: 'petrol',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 6.0,
    pickupLocationIds: ['loc-bel-air', 'loc-ns-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-ns-centar'],
    bookings: [],
    imageUrl: 'images/cars/i30-2023.jpg',
  },
  {
    id: 'car-004',
    make: 'Skoda',
    model: 'Octavia',
    year: 2020,
    fuel: 'diesel',
    transmission: 'manual',
    seats: 5,
    pricePerHour: 5.9,
    pickupLocationIds: ['loc-bel-centar', 'loc-nis-centar'],
    returnLocationIds: ['loc-bel-centar', 'loc-nis-centar'],
    bookings: [
      {
        carId: 'car-004',
        pickupLocationId: 'loc-nis-centar',
        returnLocationId: 'loc-bel-centar',
        start: d('2025-08-13T07:00:00Z'),
        end: d('2025-08-13T20:00:00Z'),
      },
    ],
    imageUrl: 'images/cars/octavia-2020.jpg',
  },
  {
    id: 'car-005',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    fuel: 'electric',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 9.5,
    pickupLocationIds: ['loc-bel-air'],
    returnLocationIds: ['loc-bel-air', 'loc-bel-centar'],
    bookings: [
      {
        carId: 'car-005',
        pickupLocationId: 'loc-bel-air',
        returnLocationId: 'loc-bel-air',
        start: d('2025-08-15T09:00:00Z'),
        end: d('2025-08-15T14:00:00Z'),
      },
    ],
    imageUrl: 'images/cars/model3-2024.webp',
  },
  {
    id: 'car-006',
    make: 'BMW',
    model: '3 Series',
    year: 2022,
    fuel: 'petrol',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 8.5,
    pickupLocationIds: ['loc-bel-air', 'loc-ns-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-ns-centar'],
    bookings: [],
    imageUrl: 'images/cars/bmw-3series-2022.jpg',
  },
  {
    id: 'car-007',
    make: 'Audi',
    model: 'A4',
    year: 2021,
    fuel: 'diesel',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 8.0,
    pickupLocationIds: ['loc-bel-centar', 'loc-nis-centar'],
    returnLocationIds: ['loc-bel-centar', 'loc-nis-centar'],
    bookings: [],
    imageUrl: 'images/cars/audi-a4-2021.avif',
  },
  {
    id: 'car-008',
    make: 'Ford',
    model: 'Focus',
    year: 2020,
    fuel: 'petrol',
    transmission: 'manual',
    seats: 5,
    pricePerHour: 5.5,
    pickupLocationIds: ['loc-bel-air', 'loc-bel-centar', 'loc-nis-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-bel-centar'],
    bookings: [
      {
        carId: 'car-008',
        pickupLocationId: 'loc-bel-air',
        returnLocationId: 'loc-bel-centar',
        start: d('2025-08-16T10:00:00Z'),
        end: d('2025-08-16T14:00:00Z'),
      },
    ],
    imageUrl: 'images/cars/ford-focus-2020.webp',
  },
  {
    id: 'car-009',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    fuel: 'diesel',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 9.0,
    pickupLocationIds: ['loc-bel-air'],
    returnLocationIds: ['loc-bel-air', 'loc-bel-centar'],
    bookings: [],
    imageUrl: 'images/cars/mercedes-cclass-2023.jpg',
  },
  {
    id: 'car-010',
    make: 'Kia',
    model: 'Ceed',
    year: 2022,
    fuel: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 6.3,
    pickupLocationIds: ['loc-ns-centar', 'loc-nis-centar'],
    returnLocationIds: ['loc-ns-centar', 'loc-nis-centar'],
    bookings: [],
    imageUrl: 'images/cars/kia-ceed-2022.jpg',
  },
  {
    id: 'car-011',
    make: 'Peugeot',
    model: '308',
    year: 2021,
    fuel: 'petrol',
    transmission: 'manual',
    seats: 5,
    pricePerHour: 5.7,
    pickupLocationIds: ['loc-bel-air', 'loc-bel-centar', 'loc-ns-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-bel-centar'],
    bookings: [],
    imageUrl: 'images/cars/peugeot-308-2021.jpg',
  },
  {
    id: 'car-012',
    make: 'Renault',
    model: 'Megane',
    year: 2020,
    fuel: 'diesel',
    transmission: 'manual',
    seats: 5,
    pricePerHour: 5.4,
    pickupLocationIds: ['loc-bel-air', 'loc-nis-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-nis-centar'],
    bookings: [],
    imageUrl: 'images/cars/renault-megane-2020.jpg',
  },
  {
    id: 'car-013',
    make: 'Opel',
    model: 'Astra',
    year: 2023,
    fuel: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 6.7,
    pickupLocationIds: ['loc-bel-centar', 'loc-ns-centar'],
    returnLocationIds: ['loc-bel-centar', 'loc-ns-centar'],
    bookings: [
      {
        carId: 'car-013',
        pickupLocationId: 'loc-bel-centar',
        returnLocationId: 'loc-ns-centar',
        start: d('2025-08-14T08:00:00Z'),
        end: d('2025-08-14T18:00:00Z'),
      },
    ],
    imageUrl: 'images/cars/opel-astra-2023.jpg',
  },
  {
    id: 'car-014',
    make: 'Mazda',
    model: '3',
    year: 2024,
    fuel: 'petrol',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 7.2,
    pickupLocationIds: ['loc-bel-air', 'loc-bel-centar'],
    returnLocationIds: ['loc-bel-air', 'loc-bel-centar', 'loc-nis-centar'],
    bookings: [],
    imageUrl: 'images/cars/mazda-3-2024.avif',
  },
  {
    id: 'car-015',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    fuel: 'hybrid',
    transmission: 'automatic',
    seats: 5,
    pricePerHour: 6.9,
    pickupLocationIds: ['loc-ns-centar', 'loc-bel-centar'],
    returnLocationIds: ['loc-ns-centar', 'loc-bel-centar', 'loc-bel-air'],
    bookings: [],
    imageUrl: 'images/cars/honda-civic-2022.jpg',
  },
];

export const brands: Brand[] = [
  { id: 'toyota', name: 'Toyota', logoUrl: 'images/brands/toyota.png' },
  {
    id: 'volkswagen',
    name: 'Volkswagen',
    logoUrl: 'images/brands/volkswagen.png',
  },
  { id: 'hyundai', name: 'Hyundai', logoUrl: 'images/brands/hyundai.png' },
  { id: 'skoda', name: 'Skoda', logoUrl: 'images/brands/skoda.png' },
  { id: 'tesla', name: 'Tesla', logoUrl: 'images/brands/tesla.png' },
  { id: 'bmw', name: 'BMW', logoUrl: 'images/brands/bmw.png' },
  { id: 'audi', name: 'Audi', logoUrl: 'images/brands/audi.png' },
  { id: 'ford', name: 'Ford', logoUrl: 'images/brands/ford.png' },
  {
    id: 'mercedes',
    name: 'Mercedes-Benz',
    logoUrl: 'images/brands/mercedes.png',
  },
  { id: 'kia', name: 'Kia', logoUrl: 'images/brands/kia.png' },
  { id: 'peugeot', name: 'Peugeot', logoUrl: 'images/brands/peugeot.png' },
  { id: 'renault', name: 'Renault', logoUrl: 'images/brands/renault.png' },
  { id: 'opel', name: 'Opel', logoUrl: 'images/brands/opel.png' },
  { id: 'mazda', name: 'Mazda', logoUrl: 'images/brands/mazda.png' },
  { id: 'honda', name: 'Honda', logoUrl: 'images/brands/honda.png' },
];
